# Generated by Django 5.1.5 on 2025-04-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0003_remove_projectsdetails_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectattachment',
            old_name='file',
            new_name='files',
        ),
    ]
