# Generated by Django 5.1.5 on 2025-05-03 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_details', '0002_organisation_parent_organisation'),
        ('project_details', '0004_rename_file_projectattachment_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_member_organisation', to='organisation_details.organisation'),
        ),
    ]
