# Generated by Django 5.1.5 on 2025-05-03 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0005_projectmember_organisation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='project_asignee',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='project_asignee',
            field=models.ManyToManyField(related_name='project_engineers', to=settings.AUTH_USER_MODEL),
        ),
    ]
