# Generated by Django 5.1.5 on 2025-05-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0006_remove_projectmember_project_asignee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='member_id',
            new_name='assigned_project_id',
        ),
    ]
