# Generated by Django 5.1.5 on 2025-05-05 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0007_rename_member_id_projectmember_assigned_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='assigned_project_id',
            new_name='assignedproject_id',
        ),
    ]
