# Generated by Django 5.2 on 2025-05-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0008_rename_assigned_project_id_projectmember_assignedproject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='assignedproject_id',
            new_name='assigned_project_id',
        ),
    ]
