# Generated by Django 5.1.5 on 2025-05-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles_creation', '0003_add_more_permissions'),
        ('roles_creation', '0004_add_new_more_permissions'),
    ]

    operations = [
    ]
