# Generated by Django 5.1.5 on 2025-05-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_creation', '0005_merge_20250502_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ManyToManyField(blank=True, related_name='role_permissions', to='roles_creation.permission'),
        ),
    ]
