# Generated by Django 5.1.5 on 2025-05-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_details', '0002_organisation_parent_organisation'),
        ('priority', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='urgency_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='priority',
            unique_together={('organisation', 'urgency_name')},
        ),
    ]
