# Generated by Django 5.1.5 on 2025-04-28 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuecategory',
            old_name='icon',
            new_name='icon_url',
        ),
        migrations.RenameField(
            model_name='issuetype',
            old_name='icon',
            new_name='icon_url',
        ),
    ]
