# from .base import *

# DEBUG = False

# USE_CELERY = False
# USE_SENDGRID = True

# SITE_URL = env("SITE_URL")

# # SENDGRID
# EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
# SENDGRID_API_KEY = env("SENDGRID_API_KEY")
# SENDGRID_SANDBOX_MODE_IN_DEBUG = False
# SENDGRID_ECHO_TO_STDOUT = False
# DEFAULT_FROM_EMAIL = env("SENDGRID_FROM_EMAIL")

# # Disable Celery in Render
# CELERY_BROKER_URL = None
# CELERY_RESULT_BACKEND = None

# # Security
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# TEAMS_ENABLED = True

from .base import *

DEBUG = False

USE_CELERY = False
USE_SENDGRID = True

SITE_URL = env("SITE_URL")

# SendGrid
EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
SENDGRID_API_KEY = env("SENDGRID_API_KEY")
SENDGRID_SANDBOX_MODE_IN_DEBUG = False
SENDGRID_ECHO_TO_STDOUT = False
DEFAULT_FROM_EMAIL = env("SENDGRID_FROM_EMAIL")

# No Celery in render free tier
CELERY_BROKER_URL = None
CELERY_RESULT_BACKEND = None
