# Generated by Django 5.1.5 on 2025-04-28 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Issue_category',
            new_name='service_domain',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='product_issue',
            new_name='service_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='issue_type',
        ),
    ]
