# Generated by Django 5.1.5 on 2025-05-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_ticketcomment_ticketcommentattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='summary',
            field=models.CharField(max_length=250),
        ),
    ]
