# Generated by Django 5.1.5 on 2025-05-20 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_details', '0009_rename_assignedproject_id_projectmember_assigned_project_id'),
        ('timer', '0004_alter_ticket_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='project_owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_details.projectsdetails'),
        ),
    ]
