# Generated by Django 5.1.5 on 2025-05-24 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_details', '0002_organisation_parent_organisation'),
        ('timer', '0006_remove_ticket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_organization_tickets', to='organisation_details.organisation'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='developer_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developer_organization_tickets', to='organisation_details.organisation'),
        ),
    ]
