# Generated by Django 5.1.5 on 2025-10-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0008_ticket_on_behalf_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatimer',
            name='remaining_at_pause',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
