# Generated by Django 5.1.5 on 2025-10-21 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0009_slatimer_remaining_at_pause'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_hour', models.TimeField(default='09:00')),
                ('end_hour', models.TimeField(default='18:00')),
                ('working_days', models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='slatimer',
            name='sla_hours',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('working_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='timer.workinghours')),
            ],
        ),
        migrations.AddField(
            model_name='slatimer',
            name='working_hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timer.workinghours'),
        ),
    ]
