# Generated by Django 5.1.5 on 2025-10-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0010_workinghours_slatimer_sla_hours_holiday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatimer',
            name='sla_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
