# Generated by Django 5.1.5 on 2025-11-17 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0011_alter_slatimer_sla_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('method', models.CharField(choices=[('graph_1to1', '1:1 via Graph'), ('webhook', 'Incoming Webhook'), ('channel', 'Channel via Graph')], default='graph_1to1', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='queued', max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=200, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='timer.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
