# Generated by Django 5.1.5 on 2025-09-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_reports_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='title',
            field=models.TextField(),
        ),
    ]
