# Generated by Django 5.1.5 on 2025-10-16 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_history_is_read_alter_history_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='history.history'),
        ),
    ]
