# Generated by Django 5.1.5 on 2025-10-16 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_attachment_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_attachments', to='history.reports'),
        ),
    ]
