# Generated by Django 5.1.5 on 2025-04-27 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_article', '0002_initial'),
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='timer.ticket'),
        ),
    ]
