# Generated by Django 5.1.5 on 2025-07-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_article', '0003_initial'),
        ('timer', '0008_ticket_on_behalf_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgearticle',
            name='ticket',
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='related_tickets',
            field=models.ManyToManyField(blank=True, related_name='knowledge_articles', to='timer.ticket'),
        ),
    ]
