# Generated by Django 5.1.5 on 2025-04-27 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('resolution_id', models.AutoField(primary_key=True, serialize=False)),
                ('resolution_description', models.TextField(blank=True, null=True)),
                ('resolution_type', models.CharField(choices=[('fixed', 'Fixed'), ('cannot reproduce', 'Cannot Reproduce'), ('Not a bug', 'Not a Bug'), ('solved by workaround', 'Solved by Workaround'), ('user instruction provided', 'User Instruction Provided'), ('withdrawn by user', 'Withdrawn by User'), ('no solution availabale', 'No Solution Available'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('known error', 'Known Error'), ('hardware failure', 'Hardware Failure'), ('software failure', 'Software Failure'), ('network failure', 'Network Failure'), ('implemented', 'Implemented'), ('other', 'Other')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('incident_based_on', models.CharField(choices=[('none', 'None'), ('access issues', 'Access Issues'), ('configuration', 'Configuration'), ('data quality', 'Data Quality'), ('development', 'Development'), ('infrastructure', 'Infrastructure'), ('missing user knowledge', 'Missing User Knowledge'), ('mistake', 'Mistake'), ('short dump', 'Short Dump'), ('work flow issue', 'Work Flow Issue'), ('others', 'Others')], max_length=100)),
                ('incident_category', models.CharField(choices=[('none', 'None'), ('development activities needed', 'Development Activities Needed'), ('incident of sr category', 'Incident of SR Category'), ('dependency with third part service provider', 'Dependency with Third Party Service Provider'), ('inappropriate incidents(incident not reproduceable, withdrawl requests)', 'Inappropriate Incidents(Incident not Reproduceable, Withdrawl Requests)'), ('other', 'Other')], max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='resolution_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
