# Generated by Django 5.1.5 on 2025-06-02 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolution', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='efforts_consumed',
            field=models.CharField(blank=True, help_text='Time in HH:MM format (e.g., 02:30 for 2 hours 30 minutes)', max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Efforts consumed must be in HH:MM format (e.g., 02:30)', regex='^([0-9]{1,2}):([0-5][0-9])$')]),
        ),
    ]
