# Generated by Django 5.2 on 2025-05-11 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_details', '0002_organisation_parent_organisation'),
        ('personal_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='organisation_details.employee'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
