# Generated by Django 5.1.5 on 2025-10-27 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_details', '0002_organisation_parent_organisation'),
        ('timer', '0011_alter_slatimer_sla_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='working_hours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timer.workinghours'),
        ),
    ]
